### PR TITLE
fix: update recovery for non-car files

### LINKED ISSUE #1693: nocar: Update LID recovery tool to account for non-car files
This would need be implemented along with changes required to recover without onChain details about the deals

### PR DESCRIPTION
**Pull request by LexLuthr**
Fixes #1693 
This PR uses UnsealSectorAt() to get a reader and directly feeds the reader to the commP writer. This is the same mechanism as getting a full piece from `booster-HTTP` and calculating commP on it.

### CODE REVIEW

File: cmd/boostd/recover.go [hunk 1]
```diff
@@ -670,14 +661,13 @@ func processPiece(ctx context.Context, sectorid abi.SectorNumber, chainDealID ab
...
 
-		//fmt.Println("CommP CID: ", encoder.Encode(commp.PieceCID))
-		//fmt.Println("Piece size: ", types.NewInt(uint64(commp.PieceSize.Unpadded().Padded())))
-
 		if !commp.PieceCID.Equals(piececid) {
 			return fmt.Errorf("calculated commp doesnt match on-chain data, expected %s, got %s", piececid, commp.PieceCID)
 		}
 	}
 
+	_ = reader.Close()
```
Comment (dirkmc) [inline cmd/boostd/recover.go:669]:
```suggestion
```

File: cmd/boostd/recover.go [hunk 2]
```diff
@@ -580,15 +580,6 @@ func processPiece(ctx context.Context, sectorid abi.SectorNumber, chainDealID ab
```
Comment (dirkmc) [inline cmd/boostd/recover.go:580]: I'd suggest putting `defer reader.Close()` right after the error check above

File: cmd/boostd/recover.go [hunk 3]
```diff
@@ -577,22 +577,9 @@ func processPiece(ctx context.Context, sectorid abi.SectorNumber, chainDealID ab
 	if !isUnsealed {
 		return fmt.Errorf("sector %d is not unsealed", sid)
 	}
+	defer reader.Close()
```
Comment (dirkmc) [inline cmd/boostd/recover.go:580]: The defer should go before the isUnsealed check above

**Review by dirkmc — APPROVED** [review]
